### ISSUE TITLE
Feature: Make configurable plausible URL (not just the domain)

### ISSUE THREAD

**Issue by siailya** [RealOrangeOne/django-plausible#6]
I have install plausible plugin to my wagtail site and try to configure it. But in the admin panel I can only configure plausible domain without protocol scheme (http/https).

If I specify protocol in this field I have scripts src like "https://http://mydomain". It will be great possibility to specify full URL to plausible instance with the protocol (http/https)

It works well when I specify http in script manually (without plugins), so I think will be great also to have possibility configure script with http with plugin

_Some additional info: in the template tag (`django-plausible/plausible/templatetags/plausible.py`) https scheme is hardcoded_

**Comment by RealOrangeOne** [comment]
It's 2023, things should run over HTTPS. I'm not sure if it supports running Plausible on a sub-path (it probably does), but I could see value for _that_.

Hard-coding that was intentional, and I don't want to support `http` URLs.
